# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eduardorvieira
# "service" is the name of this project. This will also be added to your AWS resource names.
service: moneymind

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "*"

plugins:
  - serverless-offline

functions:
  createExpense:
    name: ${self:service}-createExpense
    handler: src/expense/functions/createExpense.handler
    events:
      - http:
          method: post
          path: /expense

  readExpense:
    name: ${self:service}-readExpense
    handler: src/expense/functions/readExpense.handler
    events:
      - http:
          method: get
          path: /expense/{id}

resources:
  - ${file(resources/dynamoDB.yml)}